name: Code Analysis

on:
  push:
    branches:
      - '**' # Triggers on push to any branch

jobs:
  analyze_code: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract repository name
      id: extract_repo_name
      run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

    - name: Send POST request to code analysis API
      id: send_request
      run: |
        owner=${{ github.repository_owner }}
        repo=${{ env.REPO_NAME }}
        token=${{ secrets.MY_TOKEN }}
        echo "OWNER: $owner"
        echo "REPO: $repo"
        response=$(curl -s -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=$owner&repo=$repo&token=$token")
        
        # Check if the curl request was successful
        if [ $? -ne 0 ]; then
          echo "Curl request failed"
          exit 1
        fi
        
        echo "Response: $response"
        echo "response=$response" >> $GITHUB_ENV

    - name: Check API response
      run: |
        if [ "${{ env.response }}" != "true" ]; then
          echo "API Response is false. Failing the job."
          exit 1
        else
          echo "API Response is true. Job succeeded."
        fi
